trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'         #not working needs changes

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml                
  displayName: 'Run a multi-line script'   #test task not working needs changes
- path: azure-pipelines.yml
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName:  'Run as per pipesline' #test task not working needs changes