trigger:
  branches:
    include:
      - main  # Change branch name if needed

pool:
  vmImage: 'ubuntu-latest'  # Use 'windows-latest' for Windows builds

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build the application'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        packageType: 'sdk'
        version: '6.x'  # Update if using .NET 7 or later

    - script: |
        dotnet bu
